local bunkerTopLeft = {x = 4626, y = 15547, z = -1}
local RavenCreekApts = {
    doorKeys = {
        name = "Raven Creek Apartments Key",
        doors = {
            { x = 4629, y = 15560, z = 1, },
            { sprite = "location_community_police_01_5", x = 4630, y = 15571, z = 0, },
            { sprite = "fixtures_doors_fences_01_25", x = 4632, y = 15555, z = 0, },
        },
    },
    map = { name = "DWAP_RCA_StashMap1", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 4625, y = 15557, z = 0, },
            fakeGenerators = {
                { x = 4618, y = 15558, z = -1, },
                { x = 4630, y = 15556, z = 3, },
            },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = 4628, y = 15555, z = 3 },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4628,
                        y = 15555,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4628,
                        y = 15556,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4628,
                        y = 15558,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4628,
                        y = 15559,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4629,
                        y = 15555,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4629,
                        y = 15556,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4629,
                        y = 15558,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 4629,
                        y = 15559,
                        z = 4,
                        pb = 1,
                        spawn = false,
                    },
                },
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_73", x = 4625, y = 15562, z = 0, sourceType="generator", source = 1, },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_8", x = 4622, y = 15556, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 4625, y = 15556, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_26", x = 4625, y = 15557, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_14", x = 4626, y = 15555, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_27", x = 4626, y = 15557, z = 1, sourceType="tank", source = 1, },

        { sprite = "fixtures_sinks_01_8", x = 4622, y = 15556, z = 2, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 4625, y = 15556, z = 2, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_26", x = 4625, y = 15557, z = 2, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_14", x = 4626, y = 15555, z = 2, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_27", x = 4626, y = 15557, z = 2, sourceType="tank", source = 1, },

        { sprite = "fixtures_sinks_01_8", x = 4622, y = 15556, z = 3, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_1", x = 4625, y = 15556, z = 3, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_26", x = 4625, y = 15557, z = 3, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_14", x = 4626, y = 15555, z = 3, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_27", x = 4626, y = 15557, z = 3, sourceType="tank", source = 1, },
    },
    objectSpawns = {
        -- { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 6381, y = 16223, z = 0, },
    },
    loot = {
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            special = "essentials",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y,z=bunkerTopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+1,z=bunkerTopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
    },
}

return RavenCreekApts
